language: go
go:
  - 1.10.x
before_install:
  - go get golang.org/x/tools/cmd/cover golang.org/x/lint/golint
  - >
    ver=1.4.4 &&
    wget -nv http://www.apache.org/dist/hbase/$ver/hbase-$ver-bin.tar.gz &&
    echo "83DF3A60E937FBE38201AF249A638027541372764C05199EC64AB2220040C6A75BE4EFE7EE952FF6A9689478CDB05B860243403FB6366DB211B85CA5B1DB11C8  hbase-$ver-bin.tar.gz" | sha512sum --strict --check - &&
    tar zxf hbase-$ver-bin.tar.gz --exclude=docs &&
    ln -s hbase-$ver hbase
install:
  - ./install_ci.sh
after_success:
  - make coverdata
  - bash <(curl -s https://codecov.io/bash)
before_script:
  - hbase/bin/hbase-daemon.sh --config hbase/conf start master
script:
  - make -j4 jenkins GOTEST_FLAGS=-v
