name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: [~1.24, ^1]
    steps:
      - uses: actions/checkout@v5

      - name: Setup | Download HBase
        run: |
          ver=2.6.2 &&
          wget -nv https://archive.apache.org/dist/hbase/$ver/hbase-$ver-bin.tar.gz &&
          echo "FAF5F0F1BEC804E8C54D74E7EB9DDD7AFD22047DA086DD6ED1709DB3ADCF034F8E69208A94655575AB322BEABCDB7C8F85D9B8FCA07902F0BE34B68FED1EA331  hbase-$ver-bin.tar.gz" | sha512sum --strict --check - &&
          tar zxf hbase-$ver-bin.tar.gz --exclude=docs &&
          ln -s hbase-$ver hbase

      - name: Setup | Config HBase
        # quick and dirty sed script to insert config into
        # hbase-site.xml.
        #
        # Set scanner timeout to 5s from default of 60s, to make tests
        # for scanner expiration faster.
        #
        # Effectively disable the balancer by setting period to very large number. Tests need to move regions
        # to new regionservers themselves when running in multi-regionserver set up.
        #
        # Run the cluster in pseudo-distributed mode. Allows for adding more than 1 regionserver for tests
        # that require running on a multi-regionserver set up.
        run: |
          sed -i '/<\/configuration>/i \
          <property><name>hbase.client.scanner.timeout.period</name><value>5000</value></property>\
          <property><name>hbase.balancer.period</name><value>2147483647</value></property>
          ' hbase/conf/hbase-site.xml

          sed -i '
          /<name>hbase.cluster.distributed<\/name>/{
          n
          s/<value>false<\/value>/<value>true<\/value>/
          }
          ' hbase/conf/hbase-site.xml

      - name: Setup | Start HBase
        run: |
          hbase/bin/hbase-daemon.sh --config ./hbase/conf start zookeeper
          hbase/bin/hbase-daemon.sh --config hbase/conf start master
          hbase/bin/local-regionservers.sh start 1

      - name: Setup | Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Check
        run: make check

      - name: Test
        run: make integration_cover HBASE_HOME=hbase

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5

      - name: Upload HBase logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: hbase-logs
          path: hbase/logs/
